language: java

jdk:
  - openjdk11

script:
  - cd kaftter-consumer && ./gradlew clean build test --info --stacktrace && cd ..
  - cd kaftter-api && ./gradlew clean build test --info --stacktrace && cd ..
