addons:
  sonarcloud:
    organization: 3ldr0n
    token:
      secure: $SONAR_KEY

matrix:
  include:
  - language: java
    jdk:
    - openjdk11
    before_script:
    - cd kaftter-api
    script:
    - ./gradlew clean
    - ./gradlew build -x test
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - ./gradlew sonarqube -Dsonar.login=$SONAR_KEY
  - language: java
    jdk:
    - openjdk11
    before_script:
    - cd kaftter-consumer
    script:
    - ./gradlew clean
    - ./gradlew build -x test
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - ./gradlew sonarqube -Dsonar.login=$SONAR_KEY
  - language: scala
    jdk:
    - openjdk11
    scala:
    - 2.12.10
    before_script:
    - cd tweet-summarizer
    script:
    - sbt ++$TRAVIS_SCALA_VERSION clean
    - sbt ++$TRAVIS_SCALA_VERSION package
    - sbt ++$TRAVIS_SCALA_VERSION test
