addons:
  sonarcloud:
    organization: "3ldr0n"
    token:
      secure: $SHORTY_SONAR

matrix:
  include:
    - language: java
      jdk:
        - openjdk11
      before_script:
        - cd kaftter-api
      script:
        - ./gradlew clean
        - ./gradlew build -x test
        - ./gradlew test
        - ./gradlew jacocoTestReport --info
        - ./gradlew sonarqube -Dsonar.login=$SHORTY_SONAR --info --stacktrace
    - language: java
      jdk:
        - openjdk11
      before_script:
        - cd kaftter-consumer
      script:
        - ./gradlew clean
        - ./gradlew build -x test
        - ./gradlew test
        - ./gradlew jacocoTestReport --info
        - ./gradlew sonarqube -Dsonar.login=$SHORTY_SONAR --info --stacktrace
    - language: scala
      jdk:
        - openjdk11
      scala:
        - 2.12.10
      before_script:
        - cd tweet-summarizer
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean
        - sbt ++$TRAVIS_SCALA_VERSION package
        - sbt ++$TRAVIS_SCALA_VERSION test

env:
  global:
    secure: Yxv9D6Lhjmu2lGNIsxmmMuVFDXq93ETKcA3d9KKnT+wgN+MpYz9BUiYaisv263Ptrh3WPW3E1P+iBAzZcRzpRQ1GMI6EXT0DXZRGa4acDMN/oVHdY8nFrciIJK/5QpwpS6Zke291ytOqNNB2OvCDFXQxOvfgAF2p0Iyz8vKYaWtwtITjGfIKHYNIbC5sUnA/neDRDYFmDTcKnOukOzeBoR+UqsOCYf315GeVqndjulWA2i6XYiD9qnVJaSzr0sqvrmzSEg0Sz4+kl46zRgzYfTwFg/48GTaiCRuFsGGo+VpN166s1IAcPV2wCxhsQh5gS6iyPGY+A5aLwYBqpO0nPvmiYx0D4bvhuNv1wGacxAYCADHPcNB/cIVTJBd/WLuvB4GGNZhmi0aWOD5Tq/t9YD9y8x10BdaGCjBTwS5NxFXtWpD7ByukzNOxFs1dedljXs5AJ79zwhu2m96xjtvpeBkpXm/q4cm3OvIr0cMwVOW37ePjGA0XjjVBUuJFIPYMPISSkfy+NWMdztndonGREMEhHFioIFP47kF0MyLv5xj8x+Br12a+ETN09YVeWk/3CzVdx3FnS71POePUQm441r4jdjtSnW0WPCjyMgEHPEfBQ3auO+vS17EJmWlEAj/brReJQ2YD+v+eyK0xuSI/aZURjoYxAbrfVGckC4gvJHs=
