language: java

jdk:
  - openjdk11

script:
  - cd kaftter
  - ./gradlew clean --info --stacktrace
  - ./gradlew build test --info --stacktrace
  - cd ../kaftter-api
  - ./gradlew clean --info --stacktrace
  - ./gradlew build test --info --stacktrace
