version: '3.3'

services:
  zookeeper:
    image: zookeeper:latest
    container_name: kaftter_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kaftter_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stream.tweets:6:1"

  cassandra:
    image: cassandra:3.11.4
    container_name: kaftter_cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
    restart: always
    volumes:
      - ./cassandra_data:/var/lib/cassandra
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"

