kafka:
  topic: stream.tweets
  concurrency: 4

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: tweets-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer

  data:
    cassandra:
      keyspace-name: kaftter
      schema-action: CREATE_IF_NOT_EXISTS
      contact-points: localhost
      port: 9042